pipeline {
    agent any
    tools { 
        maven 'MAVEN_3'
        jdk 'JDK 8' 
    }
    stages {
        stage ('Initialize') {
            steps {
                bat '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }
        
        stage('compile') {
		      steps {
		        bat 'mvn clean install'
		      }
		 }

        stage ('Build') {
            steps {
               bat 'cd taskmanager-api && mvn package docker:build'
            }
        }
    }
}